server:
  port: 8080

application:
  title: Api gateway
  version: SNAPSHOT-1.0
spring-boot:
  version: 2.5.7

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: Auth-Service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: User_Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/